"""empty message

Revision ID: 8a0949211595
Revises: 89b08346afb2
Create Date: 2020-01-06 20:54:47.961891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a0949211595'
down_revision = '89b08346afb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'AvgEv',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('product', 'TotalEvCount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'TotalEvCount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('product', 'AvgEv',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('member', 'TotalEvCount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('member', 'AvgEv',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
